### ISSUE TITLE
Running the code, but nothing happened!

### ISSUE THREAD

**Issue by accountvb** [eladrich/pixel2style2pixel#80] opened 2021-02-05 21:23 UTC
Hello, I'm kind of noob, so thanks for dealing with my question even if it is about basics for you!
I tried to run the code several times on both windows and wsl ubuntu but I never could make it run it,
I followed the instructions as explained but unfortunately, nothing happened when i run the python scripts/inference.py

here is a screenshot
https://i.ibb.co/bmNnXM1/Capture-d-cran-40.png

Thank you 👍

**Comment by yuval-alaluf** [comment] 2021-02-06 07:41
Interesting.  
I'm not sure exactly what could be causing this, but I have a hunch.  
Can you try running again and after a few seconds kill the process (press ctl + c). Can you then send me the logs you see there?

**Comment by accountvb** [comment] 2021-02-07 09:03
Tried several times but nothing happened!
i do not what is the problem!
anyways, thanks man for trying helping me

**Comment by yuval-alaluf** [comment] 2021-02-07 10:32
Not sure I follow. 
Can you please try running, then pressing ctrl+c to stop the execution, and sending the stack trace. 
If you can provide more information I can try to assist. 
If you press and hold ctrl+c you should see some stack trace of the execution.  

In any case, can you try providing some more details about your environment (e.g. gpu, cuda version, pytorch version, etc)

**Comment by accountvb** [comment] 2021-02-13 14:32
Here is the info

I'm using Ubuntu 20.04.1 LTS on windwos WSL
Python 3.6.7 :: Anaconda
CUDA Version 11.0.228
GPU RTX 2060 MAX


The stack trace/
^CTraceback (most recent call last):
  File "scripts/inference.py", line 19, in <module>
    from models.psp import pSp
  File "/mnt/c/Users/asus/Documents/Projects/pixel2style2pixel/models/psp.py", line 9, in <module>
    from models.encoders import psp_encoders
  File "/mnt/c/Users/asus/Documents/Projects/pixel2style2pixel/models/encoders/psp_encoders.py", line 8, in <module>
    from models.stylegan2.model import EqualLinear
  File "/mnt/c/Users/asus/Documents/Projects/pixel2style2pixel/models/stylegan2/model.py", line 7, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/mnt/c/Users/asus/Documents/Projects/pixel2style2pixel/models/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/mnt/c/Users/asus/Documents/Projects/pixel2style2pixel/models/stylegan2/op/fused_act.py", line 13, in <module>
    os.path.join(module_path, 'fused_bias_act_kernel.cu'),
  File "/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 974, in load
    keep_intermediates=keep_intermediates)
  File "/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1183, in _jit_compile
    baton.wait()
  File "/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/utils/file_baton.py", line 49, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt

**Comment by yuval-alaluf** [comment] 2021-02-13 15:54
Thanks for providing the stack trace. The error you're getting is what I thought was happening :smile: 
It sometimes occurs with ninja where the compilation process is locked by a process. To fix this, try looking at the paths:
```
~/.cache/torch_extensions/fused/
~/.cache/torch_extensions/upfirdn2d/
```
(Or wherever your cache for the torch extensions is)
There, see if you have a file that ends with `.lock` or something of that nature. If so, delete the file and try re-running the script.

It may not necessarily be in the exact path I noted above. Can you try to find it using
```
find / -name "torch_extensions"
```
Please let me know if you still have trouble locating the `lock` file.

**Comment by KJYoo1989** [comment] 2021-02-16 08:43
Hello, i think my problem is related, but I am getting the error below. I tried to reinstall ninja again, but it would be most wonderful if you can help me! thank you!

```
(psp_env) ubuntu@ip-123-123-123-123:~/Downloads/pixel2style2pixel$ python scripts/inference.py --exp_dir=$HOME/Downloads/ --checkpoint_path=experiment/checkpoints/psp_ffhq_toonify.pt --data_path= experiment/face.png --test_batch_size=4 --test_workers=4 --couple_outputs
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/inference.py", line 19, in <module>
    from models.psp import pSp
  File "./models/psp.py", line 9, in <module>
    from models.encoders import psp_encoders
  File "./models/encoders/psp_encoders.py", line 8, in <module>
    from models.stylegan2.model import EqualLinear
  File "./models/stylegan2/model.py", line 7, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "./models/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "./models/stylegan2/op/fused_act.py", line 13, in <module>
    os.path.join(module_path, 'fused_bias_act_kernel.cu'),
  File "/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 974, in load
    keep_intermediates=keep_intermediates)
  File "/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1179, in _jit_compile
    with_cuda=with_cuda)
  File "/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1279, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error building extension 'fused': [1/3] c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/ubuntu/anaconda3/envs/psp_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp -o fused_bias_act.o 
In file included from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/c10/core/DeviceType.h:8:0,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp:1:
/home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp: In function ‘at::Tensor fused_bias_act(const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float, float)’:
/home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp:7:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                          ^
/home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp:13:5: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(input);
     ^~~~~~~~~~
In file included from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp:1:
/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/c10/core/DeviceType.h:8:0,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/ATen.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp:1:
/home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp:7:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                          ^
/home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp:14:5: note: in expansion of macro ‘CHECK_CUDA’
     CHECK_CUDA(bias);
     ^~~~~~~~~~
In file included from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp:1:
/home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
[2/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/ubuntu/anaconda3/envs/psp_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/ubuntu/anaconda3/envs/psp_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/Downloads/pixel2style2pixel/models/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/basic_string.h:6688:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
       __p->_M_set_sharable();
       ~~~~~~~~~^~
/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
ninja: build stopped: subcommand failed.
```

**Comment by accountvb** [comment] 2021-02-16 13:26
Thank you,

I've installed ninja and tried to run the code again, this time i got this error, can you tell me please if you know what is the problem for the moment?

Thanks


Traceback (most recent call last):
  File "scripts/inference.py", line 133, in <module>
    run()
  File "scripts/inference.py", line 39, in run
    ckpt = torch.load(test_opts.checkpoint_path, map_location='cpu')
  File "/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /tmp/pip-req-build-808afw3c/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /tmp/pip-req-build-808afw3c/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7fa6684962ad in /home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x25db (0x7fa66abf9a1b in /home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7b (0x7fa66abfaf2b in /home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6af8bb (0x7fa68b4b68bb in /home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x158ca6 (0x7fa68af5fca6 in /home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #38: __libc_start_main + 0xf3 (0x7fa699ecb0b3 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by yuval-alaluf** [comment] 2021-02-16 14:51
@accountvb , the error you're receiving is almost always because of incompatible package versions. Please make sure you have the correct package versions for torch and torchvision.

**Comment by yuval-alaluf** [comment] 2021-02-16 14:53
Hi @KJYoo1989 , it is difficult to pinpoint exactly what your error is. There are numerous other issues concerning issues with ninja, which may be of use. If you are still unable to get ninja to work, you may find better luck in rosinality's StyleGAN2 repo which also has some issues concerning ninja's installation.

**Comment by accountvb** [comment] 2021-02-16 21:09
> 
> 
> @accountvb , the error you're receiving is almost always because of incompatible package versions. Please make sure you have the correct package versions for torch and torchvision.


the 2 packages are not comptiable
    - torch==1.6.0
    - torchvision==0.4.2
when install torch==1.6.0 is says that version is not comptibale with  torchvision==0.4.2

and when i install torchvision==0.4.2 , it shows: uninstalled torch-1.6.0 then install torch-1.3.1 instead (automatically)
https://i.postimg.cc/T3bKrMtm/Capture-d-cran-5.png

**Comment by accountvb** [comment] 2021-02-16 21:18
Thank you  :)
i got another error

> --exp_dir=./output \
> --checkpoint_path=pretrained_models/psp_ffhq_encode.pt \
> --data_path=./input \
> --test_batch_size=4 \
> --test_workers=4 \
> --couple_outputs
Loading pSp from checkpoint: pretrained_models/psp_ffhq_encode.pt
Loading dataset for ffhq_encode
0it [00:00, ?it/s]
/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/numpy/core/_methods.py:234: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/numpy/core/_methods.py:195: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/mena/anaconda3/envs/psp_env/lib/python3.6/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Runtime nan+-nan


thanks for your help

**Comment by yuval-alaluf** [comment] 2021-02-17 05:01
In another issue you said you were able to get thr code to work so just for completeness in case it helps anyone else, this again seems to be an error caused by incorrect package versions. To be safe, I'll verify again that the versions listed in our conda yaml are correct. 
I am closing this issue since you were able to get your code to run.

**Closed by yuval-alaluf** 2021-02-17 05:01 UTC

**Comment by Tuo-Liang** [comment] 2024-01-22 20:38
> Thanks for providing the stack trace. The error you're getting is what I thought was happening 😄 It sometimes occurs with ninja where the compilation process is locked by a process. To fix this, try looking at the paths:
> 
> ```
> ~/.cache/torch_extensions/fused/
> ~/.cache/torch_extensions/upfirdn2d/
> ```
> 
> (Or wherever your cache for the torch extensions is) There, see if you have a file that ends with `.lock` or something of that nature. If so, delete the file and try re-running the script.
> 
> It may not necessarily be in the exact path I noted above. Can you try to find it using
> 
> ```
> find / -name "torch_extensions"
> ```
> 
> Please let me know if you still have trouble locating the `lock` file.
> 
> P.S. If this happens again, you can know that this is your problem since part of the stack trace contains the commands
> 
> ```
> baton.wait()
> time.sleep(self.wait_seconds)
> ```

He is right. it really solves the problem. But the simplest way is to delete "fused" & "upfirdn2d" dirs in the /home/.cache/torch_extensions/
